### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by bpraveen80** [testng-team/testng-eclipse#462]
In the latest version of eclipse 2019-06 for the test NG plugin 7.0.0, I am getting the error as below. How to fix this?

Error: Could not find or load main class c:\program Files\eclipse\configuration\org.eclipse.osgi\1054\0\.cp\lib\testng-remote.jar

**Comment by missedone** [comment]
could you check the installation, is it a valid jar? `c:\program Files\eclipse\configuration\org.eclipse.osgi\1054\0.cp\lib\testng-remote.jar`

you may try uninstall and re-install.

**Comment by mpet** [comment]
@bpraveen80  did you manage to fix the problem?

**Comment by mpet** [comment]
@missedone  we have reported this:
https://github.com/testng-team/testng-eclipse/issues/560
and it seems like we in **linux** don't get the testng-remote.jar in to our directory 

Q1: what are all the numbers between org.eclipse.osgi\<number here>\0.cp?
Q2: How is it transfer into this directory?

**Comment by missedone** [comment]
could you try with the latest version?
