### ISSUE TITLE
Error: Could not find or load main class org.testng.remote.RemoteTestNG when running test in Eclipse

### ISSUE THREAD

**Issue by tthach75** [testng-team/testng-eclipse#477]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
When trying to run a test in eclipse I get the following error: Error: Could not find or load main class org.testng.remote.RemoteTestNG

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
Looking into the eclipse log file I can see the java command with a very long -classpath (see attached eclipse log file).

I tried with a very basic class in two projects:
```
import org.testng.annotations.Test;

public class SimpleTest {
	@Test
	public void testClasspath() {
		System.out.print("hello there");
	}
}
```

One has a very long list of JARs and the other with only a small set of JARs. Both projects are managed by gradle. 
Running the test in the first project errors out with the error above. Running the exact same test in the second project passes.
[eclipse-error.log](https://github.com/cbeust/testng-eclipse/files/4278815/eclipse-error.log)

I think this is probably due to the long classpath issue on Windows. Are there any workarounds / solutions for this?
### The Dependency Management tool for your project

- [ ] Maven
- [x ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x ] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
could you add testng-remote to your gradle project classpath:

`org.testng.testng-remote:testng-remote-dist:1.4.0:shaded`

the equal with Maven
```xml
<repositories>
  <repository>
    <id>jcenter</id>
    <name>bintray</name>
    <url>http://jcenter.bintray.com</url>
  </repository>
</repositories>

<dependency>
  <groupId>org.testng.testng-remote</groupId>
  <artifactId>testng-remote-dist</artifactId>
  <version>1.3.0</version>
  <classifier>shaded</classifier>
</dependency>
```

**Comment by missedone** [comment]
testing-remote 1.5.1 is released to maven central
