### ISSUE TITLE
CompareResultDialog not able to display differences with org.opentest4j v1.2.0

### ISSUE THREAD

**Issue by dfs-** [testng-team/testng-eclipse#508]
### Problem Statement
As of org.opentest4j v1.2.0 the CompareResultDialog only displays N/A, where beforrhand you could see where a "string" mismatches the expected text. This is especially helpful when comparing complex types using a toString() method.

Here you can find the difference in the console output of these two versions.
[console_org.opentest4j_1.2.0.txt](https://github.com/cbeust/testng-eclipse/files/5596095/console_org.opentest4j_1.2.0.txt)
[console_org.opentest4j_1.1.1.txt](https://github.com/cbeust/testng-eclipse/files/5596096/console_org.opentest4j_1.1.1.txt)

And also how they are displayed:
| org.opentest4j | Screenshot |
| :---: | :---: |
| v1.2.0 (new)             | ![screenshot_opentest4j_1 2 0](https://user-images.githubusercontent.com/6563013/100216805-033ac780-2f13-11eb-88ce-558388768212.png) |
| v1.1.1 (old)              | ![screenshot_opentest4j_1 1 1](https://user-images.githubusercontent.com/6563013/100216806-03d35e00-2f13-11eb-989e-317d81658898.png) |

A non-educated guess is, that the new error (**org.opentest4j.AssertionFailedError**) simply does not fit the allowed regular expressions used [**here**](https://github.com/cbeust/testng-eclipse/blob/master/testng-eclipse-plugin/src/main/org/testng/eclipse/ui/CompareResultDialog.java#L94). The old opentest4j generated an **org.junit.ComparisonFailure** in the format 
```
expected:<value> but was:<value>
```
while the new one uses
```
Expecting:
 <value>
to be equal to:
 <value>
but was not.
```

### Any relate message in "Error Log" view
There are no errors, just the call to TestNG which returns successfully

### The Dependency Management tool for your project

- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@dfs- , thanks for the deep analysis, would you like to create a PR for it? thanks

**Comment by dfs-** [comment]
@missedone I probably can, but I am afraid I'm not skilled enough to test the changes. :|

**Comment by dfs-** [comment]
Nevermind; if you can read, you can do. ;)
