### ISSUE TITLE
Unable to use any urls mentioned to install plugins

### ISSUE THREAD

**Issue by mervin-john** [testng-team/testng-eclipse#527]
### Problem Statement
Unable to use any urls mentioned to install plugins
![eclipse issue](https://user-images.githubusercontent.com/53433554/126126681-85e3831e-a498-46d0-9366-d4084e88c89e.JPG)

Please suggest how to use them if the procedure is changed.

https://testng.org/testng-eclipse-update-site/6.14.3/

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [x] Linux
- [ ] OSX

**Comment by missedone** [comment]
can you try to install from local archive, download the artifact on your laptop https://testng.org/testng-eclipse-update-site/zipped/7.4.0.202106051955/org.testng.eclipse.updatesite.zip

**Comment by missedone** [comment]
It’s fixed in the latest plugin cersion
