### ISSUE TITLE
Could not initialize class org.testng.eclipse.util.ClassMethodsSuite

### ISSUE THREAD

**Issue by soundlift** [testng-team/testng-eclipse#530]
OS:  archlinux
IDE: Spring Tool Suite 4 : 4.13.1.RELEASE
![image](https://user-images.githubusercontent.com/17586660/153527275-1a76bb0b-c39d-4e7e-825a-6e2f2f053e47.png)
![image](https://user-images.githubusercontent.com/17586660/153527320-afb4aa25-d224-415f-9491-df0cbe8dad8c.png)

**Comment by jschrod** [comment]
I had the same issue.

Uninstalling TestNG plugin and installing it again solved the problem.
After re-installation, "TestNG P2 Feature" has version 7.4.0.r202105021533; similar to the other TestNG plugin components.

The newer version 7.5.0.* was brought in by Update Site https://testng.org/testng-p2-update-site
I don't know why this site happened to be in the list of available software sites in my Eclipse.
I disabled it, to prevent updates that will reintroduce this error.

**Comment by missedone** [comment]
The latest plugin version 7.8.0 solved the issue
