### ISSUE TITLE
Unable to install Testng plugin via Ansible

### ISSUE THREAD

**Issue by ashorie-clgx** [testng-team/testng-eclipse#540]
### Problem Statement
Unable to install Testng plugin "6.12.0.201709050550 - https://testng.org/testng-eclipse-update-site/6.12.0/" via Ansible.

I have placed the features and plugins folder to dropins folder inside eclipse folder where all my executables are present.

When I run the command "eclipse -clean" from cmd(Admistrator) over the server it under eclipse folder path, It installs the plugin.

The same when I try to automate via Ansible(Version 2.9) using win_command or win_shell module that interacts with cmd(Admistrator). It fails with error. Attached log file produced.

Tried troubleshooting tests:

1) Online and offline repository management for testng plugin(same error)

2)  updating the vmargs (Java Runtime Arguments)for 'Xms' and 'Xmx' to reslove "Native memory allocation (mmap)" errors.

3) updating the paging file upto 8gb from 4gbs. PFB link for same
https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows

4) updating -XX:+UseCompressedOops argument for compression during runtime.

### Any relate message in "Error Log" view
 TASK [../../ansible/roles/3rd_party_software : Run eclipse command to install plugin] ***
15:11:04  Saturday 15 October 2022  09:41:04 +0000 (0:00:05.863)       0:00:05.926 ****** 
15:11:09  fatal: [edguw1gxclbbl01]: FAILED! => {"changed": true, "cmd": "eclipse -clean", "delta": "0:00:00.793945", "end": "2022-10-15 09:41:08.162679", "msg": "non-zero return code", "rc": 1, "start": "2022-10-15 09:41:07.368734", "stderr": "Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 268435456, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)\n", "stderr_lines": ["Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 268435456, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)"], "stdout": "#\n# There is insufficient memory for the Java Runtime Environment to continue.\n# Native memory allocation (mmap) failed to map 268435456 bytes for Failed to commit area from 0x00000000c0000000 to 0x00000000d0000000 of length 268435456.\n# An error report file with more information is saved as:\n# C:\\Apps\\eclipse\\hs_err_pid1472.log\n", "stdout_lines": ["#", "# There is insufficient memory for the Java Runtime Environment to continue.", "# Native memory allocation (mmap) failed to map 268435456 bytes for Failed to commit area from 0x00000000c0000000 to 0x00000000d0000000 of length 268435456.", "# An error report file with more information is saved as:", "# C:\\Apps\\eclipse\\hs_err_pid1472.log"]}
15:11:09  
15:11:09  PLAY RECAP *********************************************************************
15:11:09  edguw1gxclbbl01            : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
15:11:09  

### The Dependency Management tool for your project

java_version: "jdk-8u202"
eclipse IDE Version: Neon.2 Release (4.6.2)

### Operating System

-  Windows Server 2019

[hs_err_pid1472.log](https://github.com/cbeust/testng-eclipse/files/9791821/hs_err_pid1472.log)

**Comment by ashorie-clgx** [comment]
I found initial issue with my installation, as WinRM utility needs to increase the below parameter.

Set-Item -Path WSMan:\localhost\Shell\MaxMemoryPerShellMB -Value 2048  # this is the max mem in MB
Restart-Service -Name WinRM

I have increased the MaxMemoryPerShellMB from 300 to 2048 now for the process to complete. 
Kindly provide me the silent argument command to install testng.

**Comment by missedone** [comment]
A simple way is to copy the update site to the [eclipse dropin folder ](https://www.ibm.com/docs/en/elms/esdr/8.2?topic=eclipse-using-dropins-folder-install-integration-plug-ins)
