### ISSUE TITLE
Getting Error while installing testNG using IBM RAD9 

### ISSUE THREAD

**Issue by GParesh** [testng-team/testng-eclipse#542]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
Whenever i am trying to install using IBM RAD9 tool using marketplace option 

Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
hostname in certificate didn't match: <testng.org> != <*.github.com> OR <*.github.com> OR <www.github.com> OR <github.io> OR <github.com> OR <*.github.io> OR <githubusercontent.com> OR <*.githubusercontent.com>

Even i had tried using the install new software option using local achieve but getting following error . 

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
Eclipse marketplace error 
Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
hostname in certificate didn't match: <testng.org> != <*.github.com> OR <*.github.com> OR <www.github.com> OR <github.io> OR <github.com> OR <*.github.io> OR <githubusercontent.com> OR <*.githubusercontent.com>

Local archieve installation error 
Cannot complete the install because one or more required items could not be found.
  Software being installed: TestNG M2E (Maven) Integration (Optional) 7.4.0.202106051955 (org.testng.eclipse.maven.feature.feature.group 7.4.0.202106051955)
  Missing requirement: TestNG Eclipse Support 7.4.0.202106051955 (org.testng.eclipse 7.4.0.202106051955) requires 'bundle org.eclipse.jdt.launching 3.10.0' but it could not be found
  Cannot satisfy dependency:
    From: TestNG 7.4.0.202106051955 (org.testng.eclipse.feature.group 7.4.0.202106051955)
    To: org.testng.eclipse [7.4.0.202106051955]
  Cannot satisfy dependency:
    From: TestNG M2E (Maven) Integration (Optional) 7.4.0.202106051955 (org.testng.eclipse.maven.feature.feature.group 7.4.0.202106051955)
    To: org.testng.eclipse.feature.group [7.1.0,8.0.0)

### The Dependency Management tool for your project

- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
TestNG M2E (Maven) Integration (Optional)  It’s optional, for local installation, you don’t need to copy it, just copy the core plugin and dependent p2 bundles
