### ISSUE TITLE
not getting TestNG in RunAs.

### ISSUE THREAD

**Issue by seenakrao** [testng-team/testng-eclipse#545]
Hi All,

Followed all the steps mentioned but no luck. I am trying to run program by doing right click but I am not getting TestNG in RunAs.

 

After trying the below steps:

Select Help / Install New Software...

Enter the update site URL in "Work with:" field:Update site for release: https://testng.org/testng-eclipse-update-site.

I am getting the following error in the alert box:

"Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.

Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.

PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

![2023-01-05_11-07-09-4db47d57a75179bf48d20c7116fb10bc](https://user-images.githubusercontent.com/77448527/210802682-43d8f897-a9ac-44f4-a526-43e5db547e08.png)

And in place of TestNG checkbox in Available Software, I get a message - unable to find https://testng.org/testng-eclipse-update-site

**Comment by sellersb** [comment]
I have the same problem. 

`Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

`javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)`


eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

**Comment by missedone** [comment]
Pls try with the latest plugin version 7.8.0
