### ISSUE TITLE
TestNG suggestion not working 

### ISSUE THREAD

**Issue by Raj7912** [testng-team/testng-eclipse#546]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows

### Eclipse ide 2022-12
"TestNG" suggestions not displayed 
![06ADA86C-16B7-41F4-87DE-768D5B44D1E9](https://user-images.githubusercontent.com/38722007/215310148-18cfedfa-9054-4342-afca-81913cf083ff.jpeg)

**Comment by Raj7912** [comment]
1)TestNG is downloaded from eclipse marketplaces 
2)Manually added build path on the project folder
3)testNG is working but no suggestions are coming

**Comment by missedone** [comment]
@Raj7912 , pls try with the latest version 7.8.0.202308061717

the content assist works for me 
<img width="778" alt="image" src="https://github.com/testng-team/testng-eclipse/assets/555134/10143333-4a89-4283-a49c-230508f4d8e3">
