### ISSUE TITLE
The TestNG eclipse update site gives error 404 which say the site do not have the file

### ISSUE THREAD

**Issue by andole-anju1** [testng-team/testng-eclipse#557]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
closing this due to lack of details
