### ISSUE TITLE
Unable to resolve error in testNG.xml file

### ISSUE THREAD

**Issue by reshma-sabu** [testng-team/testng-eclipse#558]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Suite">
  <test thread-count="5" name="Test">
    <classes>
      <class name="qatarlivestock/testcases/SuccessfullLoginTest.java"/>
    </classes>
  </test> 
</suite> 

Error displayed:

Error while downloading 'https://testng.org/testng-1.0.dtd' to 'C:\Users\190205\.lemminx\cache\https\testng.org\testng-1.0.dtd' : '[sun.security.provider.certpath.SunCertPathBuilderException] unable to find valid certification path to requested target'.

![Screenshot (38)](https://github.com/testng-team/testng-eclipse/assets/83294720/7b0ec755-ad1b-4fc9-bf88-b51b027df711)

**Comment by missedone** [comment]
if you run the test suite, does it work?

**Comment by reshma-sabu** [comment]
yes it is running the test suite

**Comment by krmahadevan** [comment]
@reshma-sabu - The error `sun.security.provider.certpath.SunCertPathBuilderException` is usually Java's way of telling you that the TestNG certificate available in https://testng.org is NOT part of your Java Keystore.

You would need to download the TestNG certificate and add it up to your keystore.

You can perhaps refer to some of these articles to learn how to do it.

https://www.identrust.com/support/howdoi/how-exportback-digital-certificate-using-microsoftr-edge

Use this tool to be able to open up your Java's default keystore and add the newly downloaded certificate. https://keystore-explorer.org/
