### ISSUE TITLE
Error: Could not find or load main class org.testng.remote.RemoteTestNG plugin 7.8.0 with Eclipse 4.24

### ISSUE THREAD

**Issue by mpet** [testng-team/testng-eclipse#560]
### Problem Statement
We cannot run our testng tests anymore with 7.8.0 plugin.
We try to run the testng tests in Eclipse from java file.

### Any relate message in "Error Log" view
Error: Could not find or load main class org.testng.remote.RemoteTestNG
Caused by: java.lang.ClassNotFoundException: org.testng.remote.RemoteTestNG

### The Dependency Management tool for your project
Maven

### Operating System
 Linux

**Comment by missedone** [comment]
hi @mpet , 
how did you install the plugin? and what's your eclipse version?

**Comment by missedone** [comment]
@mpet could you try with the latest version 7.9.0 see if the issue is solved?
