### ISSUE TITLE
Missing org.slf4j.impl during TestNG 7.8.0 Plugin install

### ISSUE THREAD

**Issue by cgarman** [testng-team/testng-eclipse#561]
### Problem Statement

I did a clean install of Eclipse 2023-09:

Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2023-09 (4.29.0)
Build id: 20230907-1323

I then tried to install the TestNG 7.8.0 through the Help->Install New Software Wizard. As I walked through that, I ended up at the *Install Remediation Page* with this error:
> Your original request has been modified.
  "Guava: Google Core Libraries for Java" will be ignored because a newer version is already installed. 
Cannot complete the install because one or more required items could not be found.
  Software being installed: TestNG P2 Feature 7.8.0.r202306071539 (org.testng.p2.feature.feature.group 7.8.0.r202306071539)
  Missing requirement: slf4j-api 1.7.36 (slf4j.api 1.7.36) requires 'java.package; org.slf4j.impl 1.6.0' but it could not be found
  Cannot satisfy dependency:
    From: TestNG P2 Feature 7.8.0.r202306071539 (org.testng.p2.feature.feature.group 7.8.0.r202306071539)
    To: org.eclipse.equinox.p2.iu; slf4j.api [1.7.36,1.7.36]

So I can't seem to get the TestNG P2 Feature with the latest version installed.

I could use some input other whether there's something I can do to fix this, or if it is something I don't need to worry about.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

Not that I could tell, aside from a repeat of the missing requirement.

### The Dependency Management tool for your project

- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [x] OSX on 12.7 (intel) and 14.1 (M2)

**Comment by missedone** [comment]
could you try with the latest version 7.9.0.202312310355

**Comment by cgarman** [comment]
@missedone looks good with version 7.9.0.202312310355
