### ISSUE TITLE
Migrate LaunchSuite and SuiteGenerator classes from "org.testng.xml" in testng codebase to here

### ISSUE THREAD

**Issue by krmahadevan** [testng-team/testng-eclipse#562]
The below two classes reside in TestNG but it is being ONLY used by the eclipse plugin. So it would make sense that we move these classes from the TestNG codebase to the testng eclipse plugin codebase.

Classes in question:

* [LaunchSuite.java](https://github.com/testng-team/testng/blob/master/testng-core/src/main/java/org/testng/xml/LaunchSuite.java)
* [SuiteGenerator](https://github.com/testng-team/testng/blob/master/testng-core/src/main/java/org/testng/xml/SuiteGenerator.java)

The above classes are being referred to in

* `org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate`
* `org.testng.eclipse.ui.util.ConfigurationHelper`
* `org.testng.eclipse.util.CustomSuite`
* `org.testng.eclipse.util.SuiteGenerator`

Please confirm once the migration is complete and I will go ahead and remove off the above two classes from the testng codebase.

ping @missedone

**Comment by missedone** [comment]
sure, i will raise the PR after the 7.9.0 release

**Comment by krmahadevan** [comment]
@missedone - Here's the PR that I have raised for TestNG https://github.com/testng-team/testng/pull/3031

**Comment by lahodaj** [comment]
I would like to ask how it was determined these classes are not used anywhere outside of the Eclipse plugin. Because the `LaunchSuite` and `SuiteGenerator` are used inside NetBeans:
https://github.com/apache/netbeans/blob/0090cf959e52e236fbba307f4b75e3cd4e91d0be/java/testng/src/org/netbeans/modules/testng/spi/XMLSuiteSupport.java#L52

**Comment by juherr** [comment]
@lahodaj Thanks for the alert. 
We are not able to know all usages of the api.
About netbeans, we tried to contact them years ago when we released testng-remote.
Are you part of the netbeans team?

**Comment by lahodaj** [comment]
@juherr

NetBeans is an Apache project now, and I am member of its PMC. Best way to contact the project is to write to `dev@netbeans.apache.org`.

Regarding testng-remote - I don't think I am an expert on test framework support in NetBeans. I peeked at the repository, but I am not completely clear on what this is doing. Are there some examples? Thanks!

**Comment by missedone** [comment]
@lahodaj regards to this particular case, you don't have to learn about testng-remote, instead, you can refer to the PR https://github.com/testng-team/testng-eclipse/pull/564/files how the testng-eclipse incorporates with the breaking change in testng itself, that said, simply copy the relate source code to NetBeans (both are apache license)
